version: '3'

services:
  grafana:
    build: .
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - grafana-configs:/etc/grafana
      - grafana-logs:/var/log/grafana

volumes:
  grafana-storage:
  grafana-configs:
  grafana-logs: