version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=6tC+GRAFANA
    volumes:
      - grafana-storage:/var/lib/grafana
      - grafana-configs:/etc/grafana
      - grafana-logs:/var/log/grafana
    command:
      - "grafana-cli plugins install grafana-piechart-panel && /run.sh"

volumes:
  grafana-storage:
    driver: local
  grafana-configs:
    driver: local
  grafana-logs:
    driver: local